In [1]:
import numpy as np

In [42]:
# page_rank returns a numpy array of the page rank of each node
# in the provided nodes
def page_rank_(A):
    print(f"""
        Running Page Rank Algorithm
        on the following matrix:

        {A}

    """)

    evalues, evectors = np.linalg.eig(A)

    p = np.argsort(evalues)[-1]
    ss = np.real(evectors[:,p])

    print(f"""
        The largest eigenvalue is {evalues[p]}
        and the corresponding steady state eigenvector is:

        {ss}
    """)

    ss = ss / np.sum(ss)
    revOrder = np.argsort(ss)
    inOrder = 1 + revOrder[::-1]
    ss = ss[inOrder-1]

    print(f"""
        PageRank Results:
            Final Order of Pages: {inOrder}
            Final Page Rank: {ss}
    """)

In [49]:
A = np.array([
    [1./60, 1./6, 19./60, 7./15, 1./60,  1./60],
    [2./15, 1./6, 19./60, 1./60, 1./60,  1./60],
    [12./15, 1./6,  1./60, 1./60, 1./60,  1./60],
    [1./60, 1./6,  1./60, 1./60, 7./15, 10./12],
    [1./60, 1./6, 19./60, 1./15, 1./60,  1/10],
    [1./60, 1./6,  1./60, 7./15, 7./15,  1/10]
])
page_rank(A)


        Running Page Rank Algorithm
        on the following matrix:

        [[0.01666667 0.16666667 0.31666667 0.46666667 0.01666667 0.01666667]
 [0.13333333 0.16666667 0.31666667 0.01666667 0.01666667 0.01666667]
 [0.8        0.16666667 0.01666667 0.01666667 0.01666667 0.01666667]
 [0.01666667 0.16666667 0.01666667 0.01666667 0.46666667 0.83333333]
 [0.01666667 0.16666667 0.31666667 0.06666667 0.01666667 0.1       ]
 [0.01666667 0.16666667 0.01666667 0.46666667 0.46666667 0.1       ]]

    

        The largest eigenvalue is (1.0282728287768843+0j)
        and the corresponding steady state eigenvector is:

        [0.43402944 0.24030045 0.40386837 0.55520673 0.25581118 0.46590835]
    

        PageRank Results:
            Final Order of Pages: [4 6 1 3 5 2]
            Final Page Rank: [0.23574411 0.19782748 0.1842915  0.17148493 0.10861896 0.10203301]
    
